import { useEffect, useState } from 'react';
import { Plus, Search, UserPlus, Users } from 'lucide-react';
import { api, getErrorMessage } from '../../lib/api';
import type { Role, User } from '../../types';
import { StatusBadge } from '../../components/StatusBadge';

export const UsersPage = () => {
  const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'student' as Role, studentCode: '', batch: 'CSE-2026-A' });
  const load = () => api.get('/users').then(({ data }) => setUsers(data.users)).catch((err) => setError(getErrorMessage(err)));
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post('/users', form); setOpen(false); setForm({ name: '', email: '', password: '', role: 'student', studentCode: '', batch: 'CSE-2026-A' }); await load(); } catch (err) { setError(getErrorMessage(err)); } };
  const filtered = users.filter((u) => `${u.name} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-stack"><section className="page-title-row"><div><p className="eyebrow-text">Identity management</p><h1>Users and access</h1><p>Create teachers and students, then control account availability.</p></div><button className="primary-button" onClick={() => setOpen((v) => !v)}><Plus size={18} />Add user</button></section>{error && <div className="alert error-alert">{error}</div>}
  {open && <section className="content-card"><div className="section-heading"><div><p className="eyebrow-text">New account</p><h2>Create user</h2></div><UserPlus /></div><form className="form-grid" onSubmit={create}><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" minLength={8} required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Role })}><option value="student">Student</option><option value="teacher">Teacher</option><option value="super_admin">Super Admin</option></select></label>{form.role === 'student' && <><label>Student ID<input value={form.studentCode} onChange={(e) => setForm({ ...form, studentCode: e.target.value })} /></label><label>Batch<input value={form.batch} onChange={(e) => setForm({ ...form, batch: e.target.value })} /></label></>}<div className="form-actions span-2"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button">Create account</button></div></form></section>}
  <section className="content-card"><div className="section-heading"><div><p className="eyebrow-text">Directory</p><h2>All platform users</h2></div><div className="search-box"><Search size={17} /><input placeholder="Search users" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Batch / subjects</th><th>Status</th></tr></thead><tbody>{filtered.map((user) => <tr key={user._id}><td><div className="table-user"><div className="avatar small">{user.name.slice(0, 2).toUpperCase()}</div><span><strong>{user.name}</strong><small>{user.email}</small></span></div></td><td><StatusBadge status={user.role} /></td><td>{user.batch ?? user.subjects?.join(', ') ?? '—'}</td><td><StatusBadge status={user.active === false ? 'inactive' : 'active'} /></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-state"><Users size={35} /><p>No users match this search.</p></div>}</div></section></div>;
};
